# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: 'dotnet build $(buildConfiguration)'
    steps:
    -  script: dotnet build --configuration $(buildConfiguration)
    - task: CmdLine@2
      displayName: 'dir debug'
      inputs:
        script: |
          cd $(Build.ArtifactStagingDirectory)
          dir /s /b
  
    - script: echo Build.SourcesDirectory = $(Build.SourcesDirectory)
    - script: echo Build.ArtifactStagingDirectory = $(Build.ArtifactStagingDirectory)

- stage: Provision
  jobs:
    - job: Provision1
    - job: Provision2
      dependsOn: Provision1
      condition: succeeded('Provision2')
    - deployment: DeployDevEnvironment
      displayName: 'deploy code to dev environment'
      dependsOn: Provions2
      
        



    
